[metadata]
name = nomadnet-core
version = attr: nomadnet_core._version.__version__
author = Mark Qvist
author_email = mark@unsigned.io
description = Nomad Network Core Library - protocol and data-model layer, UI-agnostic
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/markqvist/NomadNet
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8
install_requires =
    rns>=1.3.2
    lxmf>=1.0.0
